<link href={{asset('assets/frontend/css/bootstrap.min.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/animate.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/jquery.fancybox.min.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/font-awesome.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/fonts.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/swiper.min.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/style.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/responsive.css')}} rel="stylesheet" >
<link href={{asset('assets/frontend/css/jquery.multiselect.css')}} rel="stylesheet" >